AllCops:
  Exclude:
    - vendor/**/*

Naming/MethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics:
  Enabled: false

Metrics/LineLength:
  Max: 256

inherit_from: .rubocop_todo.yml
